[package]
name = "relayer"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
sled = "0.34.2"
anyhow = "1.0.75"
dotenv = "0.15.0"
oauth2 = "4.3.0"
async-imap = { version = "0.9.1", default-features = false, features = ["runtime-tokio"] }
async-native-tls = { version = "0.5.0", default-features = false, features = [ "runtime-tokio" ] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.68"
webbrowser = "0.8.11"
tiny_http = "0.12.0"
lettre = { version = "0.10.4", features = ["tokio1", "tokio1-native-tls"] }
ethers = "2.0.10"
email-wallet-utils = { path = "../utils" }
futures = "0.3.28"
sqlx = { version = "0.7", features = ["sqlite", "runtime-tokio"] }
regex = "1.10.2"
axum = "0.6.20"
rand = "0.8.5"
