name: Build-Test-Fmt

on:
  [push, pull_request]

jobs:
  build-test-fmt:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - run: rustup toolchain install --profile minimal
    - run: rustup default $(cat rust-toolchain)
    
    - uses: Swatinem/rust-cache@v2
    
    - name: Build
      run: cargo build
      
    - name: Test
      run: cargo test
      
    - name: Fmt
      run: cargo fmt -- --check

    - name: Clippy
      run: cargo clippy -- --deny warnings